# Generated by Django 5.1.7 on 2025-03-10 03:05

from django.db import migrations, models
# from django.utils.timezone import utc
import datetime
from django.utils import timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminpanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('product', models.CharField(max_length=100)),
            ],
        ),
      
    ]
