# Generated by Django 5.1.7 on 2025-04-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0002_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slide',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='adminpanel',
            name='product',
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='action_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='for_kids',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='horror',
            field=models.BooleanField(default=False),
        ),
    ]
