# Generated by Django 5.1.7 on 2025-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0003_delete_slide_remove_adminpanel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanel',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
