# Generated by Django 5.1.7 on 2025-04-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0004_adminpanel_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
