# Generated by Django 5.1.7 on 2025-04-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0005_adminpanel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=128)),
                ('amount', models.IntegerField(choices=[(199, 'Basic'), (499, 'Standard'), (799, 'Premium')])),
                ('cvv', models.CharField(max_length=4)),
                ('card_last_digits', models.CharField(default='1234', max_length=4)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
