# Generated by Django 5.1.7 on 2025-04-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0006_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
