# Generated by Django 5.1.7 on 2025-04-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0007_subscription_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
