# Generated by Django 5.1.7 on 2025-04-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0009_payment_delete_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
