# Generated by Django 5.1.7 on 2025-04-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0013_payment1_delete_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment1',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='payment1',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='payment1',
            name='subscription_plan',
            field=models.CharField(default='100', max_length=20),
        ),
        migrations.AddField(
            model_name='payment1',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment1',
            name='card_number',
            field=models.CharField(default='**** **** **** 1234', max_length=19),
        ),
    ]
