# Generated by Django 5.1.7 on 2025-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickapp', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanel',
            name='adventure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='comedy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='crime_thriller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='fantasy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='feelgood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='malayalam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='science_fiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='survival_movie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminpanel',
            name='tamil',
            field=models.BooleanField(default=False),
        ),
    ]
